### ISSUE TITLE
Hero block with image for VIP Area 

### ISSUE THREAD

**Issue by chicharr** [hlxsites/realmadrid#1]
Create and style the hero block for the VIP Area with images. Example: https://www.realmadrid.com/area-vip/partido-vip

<img width="383" alt="Screenshot 2023-04-21 at 17 28 54" src="https://user-images.githubusercontent.com/43381734/233675850-ee306e4f-0a6e-4eef-ac6e-396224efae59.png">

<img width="1782" alt="Screenshot 2023-04-21 at 17 24 47" src="https://user-images.githubusercontent.com/43381734/233674923-1d41b7c3-b662-492d-960b-98a59d657dd4.png">

The hero has:
* Main title `h1`
* Secondary title `h2` (Optional)
* Button CTA (Optional)
* Link CTA (Optional)
* On or more download links (Optional)

**Comment by vdua** [comment]
The styling of the hero block is a little different for different pages. Not sure how we can enable that 

The page, https://www.realmadrid.com/area-vip/partido-vip/silver-club-127, doesn't have full height image, the text is not aligned to center

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/2097597/234212796-09a3aec5-739f-400d-983c-109e7df704ce.png">
