### ISSUE TITLE
Next matches block

### ISSUE THREAD

**Issue by chicharr** [hlxsites/realmadrid#12]
Next matches are retrieved from AEM CS via a persisted graphql. Example call:

[https://publish-p47754-e237356.adobeaemcloud.com/graphql/execute.json/realmadridmastersite/matche[…]BsquadId=3kq9cckrnlogidldtdie2fkbl%3Balang=es-ES](https://publish-p47754-e237356.adobeaemcloud.com/graphql/execute.json/realmadridmastersite/matches%3BfromDate=2023-04-25T12:00%3BtoDate=2023-12-15T12:00%3BsquadId=3kq9cckrnlogidldtdie2fkbl%3Balang=es-ES)

As a particularity and due to a limitation with graphQL and Dynamic Media, the result provides de logo  publish url like:
https://publish-p47754-e237356.adobeaemcloud.com/content/dam/common/statics/public-content/badge/football/3kq9cckrnlogidldtdie2fkbl.png

and we have a servlet that converts that url into the DM url for the asset, you just have to add the ‘app’ selector and any required parameters: :https://publish-p47754-e237356.adobeaemcloud.com/content/dam/common/statics/public-content/badge/football/3kq9cckrnlogidldtdie2fkbl.app.png?wid=150

The block will grab the content from the persisted queries, filter out the matches were Real Madrid is not the `homeTeam` and render them with the same styling than in the current website.
<img width="499" alt="Screenshot 2023-04-25 at 15 55 45" src="https://user-images.githubusercontent.com/43381734/234299550-373c0133-6454-44db-af42-9e8a053a11c9.png">
<img width="1186" alt="Screenshot 2023-04-25 at 15 51 50" src="https://user-images.githubusercontent.com/43381734/234299563-13ce44e1-4734-49a8-ba03-3e9c14e09da1.png">

URL where you can see the original look and feel https://www.realmadrid.com/area-vip/partido-vip

**Comment by benpeter** [comment]
@chicharr  should that include 
- the year calendar
- the card flip?

breakpoints are kind of broken in the current website, at some point they turn from lines to cards but then are no longer scrollable. still replicate as-is?

**Comment by chicharr** [comment]
Both tabs need to be implemented:
List of matches and calendar.
Regarding the breakpoints, on mobile when you get the cards, you can still scroll horizontally.

**Comment by benpeter** [comment]
OK, cool - thanks! Only tried in Chrome and there the horizontal scroll didn't work for me. I may have been too hasty :)

**Comment by vdua** [comment]
@chicharr Will these URLs controlled by author or they can be a system level config controlled via a spreadsheet ?

**Comment by vdua** [comment]
@chicharr Will these URLs controlled by author or they can be a system level config controlled via a spreadsheet ?

**Comment by chicharr** [comment]
* we need to allow author to decide between `football` or `basketball`
* The AEM endpoint must be configurable in placeholders
* The rest of the query, I think we can hardcode it.
