### ISSUE TITLE
Cards block for VIP Area

### ISSUE THREAD

**Issue by chicharr** [hlxsites/realmadrid#14]
Implement cards block for VIP Area.
You can see it in this page of the original website: https://www.realmadrid.com/area-vip/partido-vip towards the end of the page

<img width="542" alt="Screenshot 2023-04-26 at 18 23 10" src="https://user-images.githubusercontent.com/43381734/234640370-290fcce9-b34a-41d0-8412-620593e92fef.png">

<img width="1276" alt="Screenshot 2023-04-26 at 18 22 39" src="https://user-images.githubusercontent.com/43381734/234640407-c36e54cf-1d71-4880-9dc4-48e0ecba7850.png">

**Comment by iuliag** [comment]
Hi @chicharr,
I realized this block has different cards depending on the page, i.e. the cards corresponding to the other vip pages in the submenu.
Should I include the content in some excel file and fetch it dynamically to populate the content of the cards block?

**Comment by chicharr** [comment]
Hi @iuliag 
I see the block in 3 pages:
https://www.realmadrid.com/area-vip/baloncesto-vip
https://www.realmadrid.com/area-vip/partido-vip
https://www.realmadrid.com/area-vip

In the first 2 cases, it renders in horizontal mode. 
In the case of the home page it renders vertically. The vertical render we can address it later.

There are 3 potential cards: PARTIDO VIP, TEMPORADA VIP, BALONCESTO VIP

If a card matches with the current page it doesn't show up in the block.

How I would do it:
* I would create a fragment document which contains the block with the 3 cards
* Style the block
* Include the fragment from the 3 pages.


What do you think?
