### ISSUE TITLE
A link in header takes the user to an invalid location

### ISSUE THREAD

**Issue by vdua** [hlxsites/realmadrid#146]
Clicking on the three dots on the header near to the login button takes you to an invalid location (https://main--realmadrid--hlxsites.hlx.live/sites/[object%20Object])

<img width="422" alt="image" src="https://github.com/hlxsites/realmadrid/assets/2097597/e675bd28-59e6-44c6-a910-0ac206c5a76e">

Question: What should be the correct url for that ?

**Comment by vdua** [comment]
Just found out that the link in the original website is `https://app-rm-spa-web-stg.azurewebsites.net/sobre-el-real-madrid/el-club/patrocinadores`

**Comment by iuliag** [comment]
Verified now that the PR with the fix was merged.
