### ISSUE TITLE
Improve LH Score - follow up

### ISSUE THREAD

**Issue by vdua** [hlxsites/realmadrid#148]
* In the hero block only 1 video is displayed (either desktop or mobile) but both the videos are fetched (2.5 Mbs in size).
* TBT is a little high sometimes

**Comment by chicharr** [comment]
There is a persisted query in AEM that we are calling to retrieve the content of the header and the footer.
The response contains both header and footer section. However it is being requested twice, once from the header block and another one from the footer block

**Comment by vdua** [comment]
@chicharr reopening this as the first issue is still not fixed

>In the hero block only 1 video is displayed (either desktop or mobile) but both the videos are fetched (2.5 Mbs in size).
