### ISSUE TITLE
Area VIP - hero variation for detail pages with text aligned to the left

### ISSUE THREAD

**Issue by chicharr** [hlxsites/realmadrid#180]
In detail pages hero text is aligned to the left, instead of centered as in the home and other pages.
We can probably do this either with a specific template or with a theme.

![Screenshot 2023-06-23 at 17 14 46](https://github.com/hlxsites/realmadrid/assets/43381734/bf767cdb-84eb-492e-9ac1-570b71d99d63)

This is also required to support the new page requested by RM:

![Screenshot 2023-06-23 at 17 16 23](https://github.com/hlxsites/realmadrid/assets/43381734/13ee81f7-d7d9-4f61-9129-28c5ae2b6482)

**Comment by vdua** [comment]
Updated all the pages with the new template
