### ISSUE TITLE
Bug: Initials for users with composed names are incorrect

### ISSUE THREAD

**Issue by chicharr** [hlxsites/realmadrid#211]
When a user is logged in, we show the initials in the header.  We generate the initals from the fullName see https://github.com/hlxsites/realmadrid/blob/2f4e84650d2d401863d0465440e0cd2b654b3cc5/sites/blocks/header/auth.js#L272

This algorithm fails when user has more than one name, e.g.: 

<img width="300" alt="Screenshot 2023-07-18 at 11 52 48" src="https://github.com/hlxsites/realmadrid/assets/43381734/510ea398-cb67-4a93-9d9f-449398c91e72">

When it should look like: 
<img width="282" alt="Screenshot 2023-07-18 at 11 53 24" src="https://github.com/hlxsites/realmadrid/assets/43381734/e6bf2607-a199-4b85-ba48-a7c6745d70e6">

Credentials to test: `paidfanusr-1689323330838@prd.es` / `123456AB`

**Comment by msagolj** [comment]
@chicharr Just to be sure: 
Judging by the test users profile:

![image](https://github.com/hlxsites/realmadrid/assets/37147400/6c927068-32a3-43d8-821b-b156b028eaf9)

and the expected output listed above, we use the inital of the 'first' first name ('keep-name' in above example) and the initial of the first surname  ('surname' in above example) and ignore any additional first / last names , correct ?
