### ISSUE TITLE
Tour - implement tour ticket cards block

### ISSUE THREAD

**Issue by chicharr** [hlxsites/realmadrid#40]
Mobile view:
![Screenshot 2023-05-05 at 14 25 47](https://user-images.githubusercontent.com/43381734/236457613-437af66d-4172-4907-a624-7bb82178b3b2.png)

Desktop view:
![Screenshot 2023-05-05 at 14 26 05](https://user-images.githubusercontent.com/43381734/236457610-318743a0-5a01-4093-82f1-69ca56c17153.png)

The tour ticket card can contain:
1. Image (optional)
2. Title (optional)
3. Subtitle (optional)
4. Price text (optional)
5. CTA Link 
6. additional info text (optional)
7. More info link

Some variations:
![Screenshot 2023-05-05 at 14 28 02](https://user-images.githubusercontent.com/43381734/236457589-592aa1da-a645-464d-9f45-e89031eb4de4.png)
![Screenshot 2023-05-05 at 14 27 34](https://user-images.githubusercontent.com/43381734/236457596-da209a47-0131-4e65-a31f-71d29a3423ef.png)
![Screenshot 2023-05-05 at 14 26 48](https://user-images.githubusercontent.com/43381734/236457607-d6eca2ba-4c36-4765-9a08-b137e3521339.png)

**Comment by chicharr** [comment]
RM used to have the possibility of setting up a label on top of each card, this is no longer on the website but they would like to have it again.
This is how it should look like `Top Ventas`

<img width="455" alt="Screenshot 2023-05-09 at 09 29 19" src="https://user-images.githubusercontent.com/43381734/237025941-dc7e76f8-d3fe-4b97-b273-50acd41bc2af.png">

And here is a URL where you can see the original styles: https://web.archive.org/web/20200609182813/https://www.realmadrid.com/tour-bernabeu

**Comment by chicharr** [comment]
Keep in mind this requirement:
https://adobe-dx-support.slack.com/archives/C04L2G6GF8X/p1682354887644099?thread_ts=1681892491.371789&cid=C04L2G6GF8X

We should be able to allow several cards in the hero. Maybe with carousel-like buttons?

**Comment by msagolj** [comment]
@chicharr 
> Keep in mind this requirement: https://adobe-dx-support.slack.com/archives/C04L2G6GF8X/p1682354887644099?thread_ts=1681892491.371789&cid=C04L2G6GF8X
> 
> We should be able to allow several cards in the hero. Maybe with carousel-like buttons?

The way its currently implemented on their site is that the ticket cards go over multiple rows. see for example
 https://www.realmadrid.com/tour-bernabeu/grupos and change the width of the browser window
- first cards have normal width
- then they get smaller
- then mulitiple lines with normal width again
so i guess if you have more then fit in one line it automatically adds the cards to a  new line.

**Comment by chicharr** [comment]
let's ask RM
