### ISSUE TITLE
Fix images in the vip-areas section

### ISSUE THREAD

**Issue by vdua** [hlxsites/realmadrid#49]
The images in the vip-areas are different in the original and franklin site. The reason for that is in the query-index the hero image comes for the page which is different than the image picked in the vip-areas section. We need to modify the metadata of the page and put the correct image that needs to be picked.

Also the number of area-vip section in Franklin are more than the original one.

|Original|Franklin|
|---|---|
|<img width="1259" alt="image" src="https://user-images.githubusercontent.com/2097597/237033692-eb19db16-f840-4ef4-b0ca-8b7acc56361f.png">|<img width="1260" alt="image" src="https://user-images.githubusercontent.com/2097597/237033920-e88433fb-7f57-4902-93de-cf0ee4fe16d2.png">|

**Comment by chicharr** [comment]
Discussed with RM, for now we keep the default extraction of picture and description for the index
