### ISSUE TITLE
Area VIP - Next Matches block - follow-up 

### ISSUE THREAD

**Issue by chicharr** [hlxsites/realmadrid#65]
Implement pending points

- working out the hyperlinks
- showing the add to calendar button and animation associated with it
- configuring out which months to display.
- show the correct season
- Read locale from the url
- Price is hardcoded
- Images should use web optimized url. See original ticket https://github.com/hlxsites/realmadrid/issues/12#issue-1684433086

**Comment by vdua** [comment]
@chicharr There are two parts to it

1. Fixes that were pending from my side. I have fixed them (except the optimized image)
2. Fixes that require the api to return a correct response. I have created a separate issue for that. #80
