### ISSUE TITLE
RTL - Carousel adapt for right to left direction

### ISSUE THREAD

**Issue by chicharr** [hlxsites/realmadrid#90]
For RTL the carousel should:
*  have the buttons on the left side, instead of right
* Swipe the elements to the right instead of left

Current behaviour:
https://main--realmadrid--hlxsites.hlx.page/ar/vip-area/matchday-hospitality/silver-club-127

Desired behaviour:
https://www.realmadrid.com/ar/vip-area/matchday-hospitality/silver-club-127

**Comment by chicharr** [comment]
Interesting reading on the topic: https://web.dev/learn/css/logical-properties/

**Comment by kacemait** [comment]
Hi @chicharr,
I commited/pushed the last code and I think it works as expected. 
The PR: https://github.com/hlxsites/realmadrid/pull/143/
